# Generated by Django 4.2.7 on 2023-12-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_qualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('linkedin', models.URLField()),
                ('city', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='profile')),
            ],
        ),
    ]
