# Generated by Django 4.2.7 on 2024-01-07 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_academicprojectcategory_academicproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicproject',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.academicprojectcategory'),
        ),
    ]
